# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#Paciente.create(nombres:'Roxan')
# admin
# --maneja odo
# secretaria patologia
# --pacientes de patologia
# --hospital
# --form_anatomia patologica
# --diagnosticos
# secretaria citologia
# --pacientes de citologia, liquidos, biopcias
# --hospital
# --form anatcitologia liquido, biopsias
# --diagnosticos
# secretaria de vigilancia epidemolica
# --pacientes de chagas, malaria, leishmaniasis + form chagas, malaria, leishmaniasis, tuberculosis, baciloscopia cultivos
# --hospital
# --diagnosticos
# encargada de inventarios
# --insumos reactivos
# ---cardex
# --estadisticas.


if Rol.all.count == 0
  Rol.create(:nombre => 'admin')
  Rol.create(:nombre => 'secretaria patologia')
  Rol.create(:nombre => 'secretaria citologia')
  Rol.create(:nombre => 'secretaria vigilancia epidemolica')
  Rol.create(:nombre => 'encargada inventarios')
end

if Hospital.all.count == 0
  Hospital.create(nombre: 'Huari Huari')
end

if Paciente.all.count == 0
  Paciente.create(:nombres => 'Sonia', :apellidos => 'Herrera Ramos', :telefono => 654321, :tipo => 'urbano', :sexo => 'Femenino')
  Paciente.create(:nombres => 'Delina', :apellidos => 'Herrera Ramos', :telefono => 654321, :tipo => 'urbano', :sexo => 'Femenino')
  Paciente.create(:nombres => 'Henrry', :apellidos => 'Herrera Ramos', :telefono => 654321, :tipo => 'urbano', :sexo => 'Masculino')
  Paciente.create(:nombres => 'Roxan', :apellidos => 'Herrera Ramos', :telefono => 654321, :tipo => 'urbano', :sexo => 'Femenino')
end

#InsumoReactivo.create(tipo:'reactivo')
#InsumoReactivo.create(tipo:'reactivo')
#InsumoReactivo.create(tipo:'reactivo')
#InsumoReactivo.create(tipo:'reactivo')
#InsumoReactivo.create(tipo:'insumo')
#InsumoReactivo.create(tipo:'insumo')
#InsumoReactivo.create(tipo:'insumo limpieza')
#InsumoReactivo.create(tipo:'insumo limpieza')
if User.all.count == 0
  User.create(:email => 'admin@user.com', :password => '123123123', :password_confirmation => '123123123', :rol_id => 1)
  User.create(:email => "patologia@user.com", :password => "123123123", :password_confirmation => "123123123", :rol_id => 2)
  User.create(:email => "citologia@user.com", :password => "123123123", :password_confirmation => "123123123", :rol_id => 3)
  User.create(:email => "vigilancia@user.com", :password => "123123123", :password_confirmation => "123123123", :rol_id => 4)
  User.create(:email => "invetarios@user.com", :password => "123123123", :password_confirmation => "123123123", :rol_id => 5)
end

if FormLaboratorio.all.count == 0
  FormLaboratorio.create(nombre: 'Anatomia Citologica')
  FormLaboratorio.create(nombre: 'Anatomia Patologica')
  FormLaboratorio.create(nombre: 'Biopsias')
  FormLaboratorio.create(nombre: 'Liquidos')
  FormLaboratorio.create(nombre: 'Chagas')
  FormLaboratorio.create(nombre: 'Malaria')
  FormLaboratorio.create(nombre: 'Leishmaniasis')
  FormLaboratorio.create(nombre: 'Tuberculosis')
  FormLaboratorio.create(nombre: 'Baciloscopias')
  FormLaboratorio.create(nombre: 'Cultivos')
end
if InsumoReactivo.all.count == 0
  InsumoReactivo.create(nombre: 'Xilol', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Hematoxilina de Harris', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Orange', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'E.A. 50%', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Acido clorhidrico', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Acetona', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Acohol absoluto 96%', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Alcohol Corriente', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Polymount (Xilene Bassed) x16OZ', tipo: 'reactivo', unidad_medida: 'Frasco')
  InsumoReactivo.create(nombre: 'Cubre Objetos 24x50MM  x 100UN', tipo: 'reactivo', unidad_medida: 'Caja')
  InsumoReactivo.create(nombre: 'Porta Objetos Esmerilados x 50UN', tipo: 'reactivo', unidad_medida: 'Caja')
  InsumoReactivo.create(nombre: 'Papel Filtro', tipo: 'reactivo', unidad_medida: 'Uni')
  InsumoReactivo.create(nombre: 'Bicarbonato de Sodio', tipo: 'reactivo', unidad_medida: 'Kilo')
  InsumoReactivo.create(nombre: 'Hematoxilina de Biopak', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Eosina Amarilla', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Formol al 40%', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Acido Acético Glacial', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Parafina Histologica', tipo: 'reactivo', unidad_medida: 'Kilo')
  InsumoReactivo.create(nombre: 'Cuchillos Desechables 22 x 80 MM', tipo: 'reactivo', unidad_medida: 'Caja')
  InsumoReactivo.create(nombre: 'Repelente de Parafina para Microtono', tipo: 'reactivo', unidad_medida: 'Bote')
  InsumoReactivo.create(nombre: 'Stat Pak para Inmunocromatografia', tipo: 'reactivo', unidad_medida: 'Litros')
  InsumoReactivo.create(nombre: 'Hemaglutinación', tipo: 'reactivo', unidad_medida: 'Hcg')
  InsumoReactivo.create(nombre: 'Chaga Test Elisa', tipo: 'reactivo', unidad_medida: 'Hcg')
  InsumoReactivo.create(nombre: 'Hipoclorito de Sodio al 5%', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Eppendorf 1.5 ul (microprobetas)', tipo: 'reactivo', unidad_medida: 'Ul')
  InsumoReactivo.create(nombre: 'Tips (Puntas Amarillas, Azules)', tipo: 'reactivo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Micropipetas 10-100 ul', tipo: 'reactivo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Micropipetas 2-20 ul', tipo: 'reactivo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Micropipetas 20-200 ul', tipo: 'reactivo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Micropipetas 100-1000 ul', tipo: 'reactivo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Agua Pura ph 7.2', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Giemsa (Colorante)', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Aceite de Inmersion', tipo: 'reactivo', unidad_medida: 'Litro')
  InsumoReactivo.create(nombre: 'Mondadientes', tipo: 'reactivo', unidad_medida: 'Caja')
  InsumoReactivo.create(nombre: 'Bateris de Tincion de Pap (Vidrio)', tipo: 'insumo', unidad_medida: 'Cubeta')
  InsumoReactivo.create(nombre: 'Canastillos de Tincion de Pap', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Timer (Reloj)', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Guantes Quirurgicos x 100 UN', tipo: 'insumo', unidad_medida: 'Cajas')
  InsumoReactivo.create(nombre: 'Barbijos Desechables x 50 UN', tipo: 'insumo', unidad_medida: 'Cajas')
  InsumoReactivo.create(nombre: 'Proveta de vidrio x 500 CC', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Goteras grandes de plastico', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Goteras pequeñas de plastico', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Mandiles Blancos', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Gorras Desechables', tipo: 'insumo', unidad_medida: 'cajas')
  InsumoReactivo.create(nombre: 'Piyamas', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Lancetas', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Capilares con Heparina', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Papel Filtro', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Tornadero', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Microsentrifuga', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Estufa', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Refrigerador', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Vaso ppho', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Probetas 50ml', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Probeta 250ml', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Embudo', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Tubos de Ensayo', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Jeringas 10-5 cc', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Jeringas Desechables de 3ml', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Torundero', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Pipetas Pasteur 150', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Pipetas 10ml', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Pipetas 5ml', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Pipetas 1ml', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Varilla para tinción', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Mechero de Alcohol o Bunsen', tipo: 'insumo', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Detergente Ace', tipo: 'insumo limpieza', unidad_medida: 'Bolsita')
  InsumoReactivo.create(nombre: 'Papel Higienico Color Blanco', tipo: 'insumo limpieza', unidad_medida: 'Rollo')
  InsumoReactivo.create(nombre: 'Lavandina', tipo: 'insumo limpieza', unidad_medida: 'Sachet')
  InsumoReactivo.create(nombre: 'Ambientadores Spray', tipo: 'insumo limpieza', unidad_medida: 'Frasco')
  InsumoReactivo.create(nombre: 'Jabon Liquido', tipo: 'insumo limpieza', unidad_medida: 'Frasco')
  InsumoReactivo.create(nombre: 'Bolsas Negras Grandes', tipo: 'insumo limpieza', unidad_medida: 'Paquete')
  InsumoReactivo.create(nombre: 'Bolsas Rojas Grandes', tipo: 'insumo limpieza', unidad_medida: 'Paquete')
  InsumoReactivo.create(nombre: 'Bolsas Negras Pequeñas', tipo: 'insumo limpieza', unidad_medida: 'Paquete')
  InsumoReactivo.create(nombre: 'Esponjitas de Limpieza', tipo: 'insumo limpieza', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Detergente Liquido para Pisos', tipo: 'insumo limpieza', unidad_medida: 'Frasco')
  InsumoReactivo.create(nombre: 'Jabon de Tocador', tipo: 'insumo limpieza', unidad_medida: 'Pan')
  InsumoReactivo.create(nombre: 'Toallas Desechables', tipo: 'insumo limpieza', unidad_medida: 'Rollo')
  InsumoReactivo.create(nombre: 'Escoba de Limpieza', tipo: 'insumo limpieza', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Alzador de Basura', tipo: 'insumo limpieza', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Basureros de Plastico', tipo: 'insumo limpieza', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Liquidos de Vidrio', tipo: 'insumo limpieza', unidad_medida: 'Frasco')
  InsumoReactivo.create(nombre: 'Aragan de Goma', tipo: 'insumo limpieza', unidad_medida: 'Pieza')
  InsumoReactivo.create(nombre: 'Algodón', tipo: 'insumo limpieza', unidad_medida: 'Rollo')
  InsumoReactivo.create(nombre: 'Fósforos', tipo: 'insumo limpieza', unidad_medida: 'Caja')
  InsumoReactivo.create(nombre: 'Tela Adesiva', tipo: 'insumo limpieza', unidad_medida: 'Rollo')
end
if Diagnostico.all.count == 0
  Diagnostico.create(tipo_diagnostico: 'A', despcripcion: 'PROB. LESION INTRAEPITELIAL ESCAMOSA DE BAJO GRADO (CAMBIOS CELULARES POR (HPV)')
  Diagnostico.create(tipo_diagnostico: 'A1', despcripcion: 'NOTA: SI HAY LESION SOSPECHOSA SE SUGIERE COLPOSCOPIA Y BIOPSIA')
  Diagnostico.create(tipo_diagnostico: 'A2', despcripcion: 'PROB. LESION INTRAEPITELIAL ESCAMOSA DE ALTO GRADO (NIC II O DISPLACIA  MODERADA)')
  Diagnostico.create(tipo_diagnostico: 'C', despcripcion: 'PROB. LESION INTRAEPITELIAL ESCAMOSA DE ALTO GRADO (NIC III O CA IN SITU)')
  Diagnostico.create(tipo_diagnostico: 'C1', despcripcion: 'PROB. LESION INTRAEPITELIAL DE ALTO GRADO')
  Diagnostico.create(tipo_diagnostico: 'C2', despcripcion: 'PROB. LESION INTRAEPITELIAL DE ALTO GRADO CON CARACTERISTICAS SOSPECHOSAS DE INVASION')
  Diagnostico.create(tipo_diagnostico: 'C3', despcripcion: 'ESCAMOSA Y GLANDULAR')
  Diagnostico.create(tipo_diagnostico: 'C4', despcripcion: 'MUESTRA MAL FIJADA')
  Diagnostico.create(tipo_diagnostico: 'C5', despcripcion: 'CA INVASOR')
  Diagnostico.create(tipo_diagnostico: 'C6', despcripcion: 'NOTA: FAVOR TOMAR OTRA MUESTRA')
  Diagnostico.create(tipo_diagnostico: 'C7', despcripcion: 'SE SUGIERE BIOPCIA URGENTE')
  Diagnostico.create(tipo_diagnostico: 'D', despcripcion: 'PROBABLE ADENOCARCINOMA DE ORIGEN ENDOCERVICAL')
  Diagnostico.create(tipo_diagnostico: 'D1', despcripcion: 'PROBABLE ADENOCARCINOMA DE ORIGEN ENDOMETRIAL')
  Diagnostico.create(tipo_diagnostico: 'D2', despcripcion: 'MUESTRA ESCASA')
  Diagnostico.create(tipo_diagnostico: 'D3', despcripcion: 'PROBABLE CARCINOMA SIN OTRAS ESPECIFICACIONES (NOS)')
  Diagnostico.create(tipo_diagnostico: 'D4', despcripcion: 'PROBABLE CARCINOMA ADENOESCAMOSO')
  Diagnostico.create(tipo_diagnostico: 'D5', despcripcion: 'BIOPSIA POR COLPOSCOPIA URGENTE')
  Diagnostico.create(tipo_diagnostico: 'D6', despcripcion: 'CARCINOMA INVASOR EPIDERMOIDE')
  Diagnostico.create(tipo_diagnostico: 'E', despcripcion: 'PROBABLE CARCINOMA ESCAMOSO')
  Diagnostico.create(tipo_diagnostico: 'E1', despcripcion: 'CARCINOMA INDIFERENCIADO')
  Diagnostico.create(tipo_diagnostico: 'F1', despcripcion: 'FROTIS ATROFICO')
  Diagnostico.create(tipo_diagnostico: 'F2', despcripcion: 'FROTIS HEMORRAGICO')
  Diagnostico.create(tipo_diagnostico: 'F3', despcripcion: 'FROTIS HIPOTROFICO')
  Diagnostico.create(tipo_diagnostico: 'F4', despcripcion: 'FROTIS EUTROFICO')
  Diagnostico.create(tipo_diagnostico: 'F5', despcripcion: 'FROTIS MUY GRUESO')
  Diagnostico.create(tipo_diagnostico: 'F6', despcripcion: 'FROTIS GRUESO')
  Diagnostico.create(tipo_diagnostico: 'F8', despcripcion: 'NOTA: MUESTRA INADECUADA PARA LA EVALUACIÓN HORMONAL')
  Diagnostico.create(tipo_diagnostico: 'F9', despcripcion: 'NOTA: LLAMA LA ATENCION EL ALTO INDICE DE MADURACION')
  Diagnostico.create(tipo_diagnostico: 'G', despcripcion: 'MUESTRA INSUFICIENTE POR AUSENCIA DE CÉLULAS')
  Diagnostico.create(tipo_diagnostico: 'G1', despcripcion: 'ESCASA')
  Diagnostico.create(tipo_diagnostico: 'G10', despcripcion: 'LAMINA ROTA')
  Diagnostico.create(tipo_diagnostico: 'G2', despcripcion: 'MUESTRA INSUFICIENTE POR HEMORRAGIA')
  Diagnostico.create(tipo_diagnostico: 'G3', despcripcion: 'LIJERAMENTE INFLAMATORIO')
  Diagnostico.create(tipo_diagnostico: 'G5', despcripcion: 'ESCASA Y HEMORRAGICA')
  Diagnostico.create(tipo_diagnostico: 'G6', despcripcion: 'ESCASA E INFLAMATORIA')
  Diagnostico.create(tipo_diagnostico: 'G7', despcripcion: 'FALTA COMPONENTE ENDOCERVICAL')
  Diagnostico.create(tipo_diagnostico: 'G8', despcripcion: 'MUESTRA SATISFACTORIA')
  Diagnostico.create(tipo_diagnostico: 'G9', despcripcion: 'SE RECIBE LÁMINA SIN IDENTIFICAR')
  Diagnostico.create(tipo_diagnostico: 'GX', despcripcion: 'NO SE RECIBE LAMINA')
  Diagnostico.create(tipo_diagnostico: 'GX2', despcripcion: 'NEGATIVO INFLAMATORIO POR FLORA INESPECÍFICA')
  Diagnostico.create(tipo_diagnostico: 'GX3', despcripcion: 'FROTIS ATROFICO INTENSAMENTE INFLAMATORIO POR FLORA INESPECIFICA, SE SUGIERE TRATAR LA INFLAMA')
  Diagnostico.create(tipo_diagnostico: 'GX4', despcripcion: 'FROTIS MUY GRUESO INFLAMATORIO POR FLORA INESPECIFICA, SE SUGIERE TRATAR LA INFLAMACIÓN Y REPETIR LA MUESTRA')
  Diagnostico.create(tipo_diagnostico: 'GX5', despcripcion: 'HIPERPLACIA DE CELULAS ENDOCCERVICALES')
  Diagnostico.create(tipo_diagnostico: 'GX6', despcripcion: 'MUESTRA INSUFICIENTE POR AUCENCIA DE CELULAS')
  Diagnostico.create(tipo_diagnostico: 'GX7', despcripcion: 'LIGERAMENTE HEMORRAGICO')
  Diagnostico.create(tipo_diagnostico: 'GX8', despcripcion: 'MUESTRA INSUFICIENTE POR MALA FIJACIÓN')
  Diagnostico.create(tipo_diagnostico: 'GX9', despcripcion: 'ECTROPION SANGRANTE?')
  Diagnostico.create(tipo_diagnostico: 'GXX', despcripcion: 'LAMINA SIN FROTIS CITOLOGICO')
  Diagnostico.create(tipo_diagnostico: 'H1', despcripcion: 'CELULAS ESCAMOSAS ATIPICAS DE SIGNIFICADO INDETERMINADO ("ASCUS" - US")')
  Diagnostico.create(tipo_diagnostico: 'H10', despcripcion: 'PARA CONTROL URGENTE')
  Diagnostico.create(tipo_diagnostico: 'H2', despcripcion: 'CELULAS ESCAMOSAS ATIPICAS, SUGERENTES DE LIE DE ALTO GRADO ( " ASCUS - H " )')
  Diagnostico.create(tipo_diagnostico: 'H3', despcripcion: 'CELULAS GLANDULARES ATIPICAS, SUGERENTE DE ORIGEN ENDOMETRIAL (NOS ) SIN OTRAS ESPECIFICACIONES')
  Diagnostico.create(tipo_diagnostico: 'H4', despcripcion: 'CELULAS GLANDULARES ATIPICAS, SUGERENTES DE ORIGEN ENDOCERVICAL ( NOS ) SIN OTRAS ESPECIFICACIONES')
  Diagnostico.create(tipo_diagnostico: 'H5', despcripcion: 'CELULAS GLANDULARES ATIPICAS, SIN OTRAS ESPECIFICACIONES')
  Diagnostico.create(tipo_diagnostico: 'H6', despcripcion: 'CELULAS ENDOCERVICALES ATIPICAS, PROBABLEMENTE NEOPLASICAS')
  Diagnostico.create(tipo_diagnostico: 'H7', despcripcion: 'CELULAS GLANDULARES ATIPICAS PROBABLEMENTE NEOPLASICAS')
  Diagnostico.create(tipo_diagnostico: 'H8', despcripcion: 'PROBABLE ADENOCARCINOMA ENDOCERVICAL " IN SITU "')
  Diagnostico.create(tipo_diagnostico: 'H9', despcripcion: 'SE OBSERVAN NUCLEOS HIPERTROFICOS, PLEOMORFICOS')
  Diagnostico.create(tipo_diagnostico: 'I', despcripcion: 'NEGATIVO PARA LESION INTRAEPITELIAL O MALIGNIDAD')
  Diagnostico.create(tipo_diagnostico: 'IJ1', despcripcion: 'REACCION INFLAMATORIA NEGATIVO PARA LESION INTRAEPITELIAL O MALIGNIDAD')
  Diagnostico.create(tipo_diagnostico: 'IL', despcripcion: 'NEGATIVO LIMPIO')
  Diagnostico.create(tipo_diagnostico: 'J1', despcripcion: 'REACCIÓN INFLAMATORIA INESPECIFICA')
  Diagnostico.create(tipo_diagnostico: 'J2', despcripcion: 'REACCION INFLAMATORIA POR TRICHOMONAS')
  Diagnostico.create(tipo_diagnostico: 'J3', despcripcion: 'PRESENCIA DE ACTINOMYCES')
  Diagnostico.create(tipo_diagnostico: 'J4', despcripcion: 'CAMBIOS DE LA FLORA VAGINAL SUGERENTE DE VAGINOSIS BACTERIANA (GARDENELLA)')
  Diagnostico.create(tipo_diagnostico: 'J5', despcripcion: 'REACCION INFLAMATORIA POR CANDIDA')
  Diagnostico.create(tipo_diagnostico: 'J6', despcripcion: 'LEPTOTRIX')
  Diagnostico.create(tipo_diagnostico: 'J7', despcripcion: 'LIGERAMENTE INFLAMATORIO')
  Diagnostico.create(tipo_diagnostico: 'J8', despcripcion: 'NOTA: SE SUGIERE SE SUGIERE BIOPSIA POR COLPOSCOPIA')
  Diagnostico.create(tipo_diagnostico: 'J9', despcripcion: 'MUESTRA INSUFICIENTE POR HEMORRAGIA')
  Diagnostico.create(tipo_diagnostico: 'K', despcripcion: 'CAMBIOS CELULARES REACTIVOS SUGERENTES DE RADIOTERAPIA')
  Diagnostico.create(tipo_diagnostico: 'K1', despcripcion: 'CELULAS CELULARES REACTIVOS SUGERENTES DE DIU')
  Diagnostico.create(tipo_diagnostico: 'K2', despcripcion: 'CELULAS ESCAMOSAS QUERATINIZADAS SUGERENTES DE HIPERQUERATOSIS')
  Diagnostico.create(tipo_diagnostico: 'L1', despcripcion: 'REACCION INFLAMATORIA POR HERPES SIMPLE')
  Diagnostico.create(tipo_diagnostico: 'L2', despcripcion: 'SIGNOS SUGERENTES DE INFECCION POR VIRUS PAPILOMA (HPV)')
  Diagnostico.create(tipo_diagnostico: 'M', despcripcion: 'METAPLASIA IN MADURA')
  Diagnostico.create(tipo_diagnostico: 'M1', despcripcion: 'DISPLACIA  METAPLASICA??')
  Diagnostico.create(tipo_diagnostico: 'M2', despcripcion: 'GONOCOCO??')
  Diagnostico.create(tipo_diagnostico: 'M3', despcripcion: 'ABUNDANTES  HIFAS  MICOTICAS')
  Diagnostico.create(tipo_diagnostico: 'M4', despcripcion: 'ABUNDANTES  HIFAS')
  Diagnostico.create(tipo_diagnostico: 'M5', despcripcion: 'CLAMIDIA')
  Diagnostico.create(tipo_diagnostico: 'M6', despcripcion: 'CERVICITIS  SEVERA')
  Diagnostico.create(tipo_diagnostico: 'M7', despcripcion: 'CERVICITIS  CRONICA')
  Diagnostico.create(tipo_diagnostico: 'M8', despcripcion: 'EPITELIO DE REPARACION REACTIVA')
  Diagnostico.create(tipo_diagnostico: 'M9', despcripcion: 'EPITELIO DE REPARACION ATIPICA')
  Diagnostico.create(tipo_diagnostico: 'N', despcripcion: 'PRESENCIA DE CELULAS ENDOMETRIALES NORMALES')
  Diagnostico.create(tipo_diagnostico: 'N1', despcripcion: 'PRESENCIA DE CELULAS GLANDULARES NORMALES')
  Diagnostico.create(tipo_diagnostico: 'N2', despcripcion: 'NUMEROSOS HISTIOCITOS ALGUNOS MULTINUCLEADOS')
  Diagnostico.create(tipo_diagnostico: 'O1', despcripcion: 'NO TIENE LAMINA')
  Diagnostico.create(tipo_diagnostico: 'O2', despcripcion: 'SE SUGIERE TRATAR LA INFLAMACION Y REPETIR PARA PRECISAR DIAGNOSTICO')
  Diagnostico.create(tipo_diagnostico: 'O3', despcripcion: 'SE SUGERE TRATAR INFLAMACION Y CONTROL EN 6 MESES')
  Diagnostico.create(tipo_diagnostico: 'O4', despcripcion: 'NOTA.-  SE SUGIERE TRATAR LA INFLAMACION Y REPETIR LA MUESTRA')
  Diagnostico.create(tipo_diagnostico: 'O5', despcripcion: 'PARA CONTROL POS-TRATAMIENTO URGENTE')
  Diagnostico.create(tipo_diagnostico: 'O6', despcripcion: 'FAVOR TOMAR OTRA MUESTRA URGENTE')
  Diagnostico.create(tipo_diagnostico: 'O8', despcripcion: 'PARA CONTROL POST TRATAMIENTO')
  Diagnostico.create(tipo_diagnostico: 'P', despcripcion: 'SE SUGIERE REPETIR')
  Diagnostico.create(tipo_diagnostico: 'P1', despcripcion: 'SE SUGIERE REPETIR PARA PRECISAR DIAGNOSTICO')
  Diagnostico.create(tipo_diagnostico: 'P2', despcripcion: 'REPETIR DESPUES DE UNA SEMANA CON TRTAMIENTO ESTROGENICO')
  Diagnostico.create(tipo_diagnostico: 'Q', despcripcion: 'SE SUGIERE REPETIR PARA DESCARTAR NEOPLASIA INTRAEPITELIAL')
  Diagnostico.create(tipo_diagnostico: 'Q1', despcripcion: 'SE SUGIERE REPETIR PARA DESCARTAR CARCINOMA')
  Diagnostico.create(tipo_diagnostico: 'R', despcripcion: 'SE SUGIERE REPETIR PARA DESCARTAR PATOLOGIA ENDOCERVICAL')
  Diagnostico.create(tipo_diagnostico: 'R2', despcripcion: 'EN LA 2DA MITAD DEL CICLO')
  Diagnostico.create(tipo_diagnostico: 'S', despcripcion: 'SE SUGIERE CONTROLAR EN UN AÑO')
  Diagnostico.create(tipo_diagnostico: 'S1', despcripcion: 'SE SUGIERE CONTROLAR EN 6 MESES')
  Diagnostico.create(tipo_diagnostico: 'S3', despcripcion: 'SE SUGIERE CONTROLAR EN 3 MESES')
  Diagnostico.create(tipo_diagnostico: 'S4', despcripcion: 'SE SUGIERE CONTROLAR EN 8 MESES')
  Diagnostico.create(tipo_diagnostico: 'S5', despcripcion: 'FAVOR VERIFICAR EDAD')
  Diagnostico.create(tipo_diagnostico: 'T', despcripcion: 'CITAR A PATOLOGIA CERVICAL PARA COMPLETAR ESTUDIO')
  Diagnostico.create(tipo_diagnostico: 'T1', despcripcion: 'NOTA: SI HAY LESION CLINICA SE SUGIERE COLPOSCOPIA Y BIOPSIA')
  Diagnostico.create(tipo_diagnostico: 'U', despcripcion: 'SE SUGIERE COMPLETAR ESTUDIO CON COLPOSCOPIA Y EVENTUAL BIOPSIA')
  Diagnostico.create(tipo_diagnostico: 'U1', despcripcion: 'SE SUGIERE COMPLETAR ESTUDIO CON BIOPSIA DIRIGIDA POR COLPOSCOPIA')
  Diagnostico.create(tipo_diagnostico: 'U2', despcripcion: 'Y CURETAJE ENDOCERVICAL')
  Diagnostico.create(tipo_diagnostico: 'U3', despcripcion: 'SE SUGIERE COMPLETAR ESTUDIO CON COLPOSCOPIA Y CURETAJE FRACCIONADO')
  Diagnostico.create(tipo_diagnostico: 'U4', despcripcion: 'SE SUGIERE COMPLETAR ESTUDIO CON CURETAJE ENDOCERVICAL')
  Diagnostico.create(tipo_diagnostico: 'V', despcripcion: 'SE SUGIERE PRACTICAR CONIZACION DIAGNOSTICA')
  Diagnostico.create(tipo_diagnostico: 'V1', despcripcion: 'SE SUGIERE COMPLETAR ESTUDIO CON CURETAJE FRACCIONADO')
  Diagnostico.create(tipo_diagnostico: 'V3', despcripcion: 'DE CRAMATINA IRREGULAR')
  Diagnostico.create(tipo_diagnostico: 'W1', despcripcion: 'UNSUFICIENTE POR INTENSAMENTE INFLAMATORIO')
  Diagnostico.create(tipo_diagnostico: 'W2', despcripcion: 'PROLIFERACION DE LACTOBACILOS DE DODERLEIN')
  Diagnostico.create(tipo_diagnostico: 'W3', despcripcion: 'NEGATIVO INFLAMATORIO POR FLORA INESPECIFICA, MARCADA PROLIFERACIÓN DE DODERLEIN')
  Diagnostico.create(tipo_diagnostico: 'W4', despcripcion: 'INTENSAMENTE INFLAMARORIO POR HAEMOFULUS VAGINALIS')
  Diagnostico.create(tipo_diagnostico: 'W5', despcripcion: 'INTENSAMENTE IFLAMATORIO POR GARDENELLAS VAGINALIS')
  Diagnostico.create(tipo_diagnostico: 'WJ1', despcripcion: 'INTENSAMENTE INFLAMATORIO FLORA INESPECIFICA')
  Diagnostico.create(tipo_diagnostico: 'WJ2', despcripcion: 'INTENSAMENTE INFLAMATORIO POR TRICHOMONAS')
  Diagnostico.create(tipo_diagnostico: 'WJ4', despcripcion: 'INTENSAMENTE INFLAMATORIO POR GARDENELLA')
  Diagnostico.create(tipo_diagnostico: 'X', despcripcion: 'NOTA: INFORME RETRASADO POR CAMPAÑA')
  Diagnostico.create(tipo_diagnostico: 'X1', despcripcion: 'FAVOR REPETIR LA MUESTRA Y VERIFICAR EDAD')
  Diagnostico.create(tipo_diagnostico: 'Z', despcripcion: 'TROZOS SUELTOS DE EPITELIO NEOPLASICO')
  Diagnostico.create(tipo_diagnostico: 'Z2', despcripcion: 'HIPERTROFOCOS')
  Diagnostico.create(tipo_diagnostico: 'Z4', despcripcion: 'LAMINA CONTAMINADA POR MALA FIJACION')
  Diagnostico.create(tipo_diagnostico: 'Z5', despcripcion: 'SE OBSERVAN NUCLEOS HIPERTROFICOS E HIPERCROMATICOS DE CROMATINA IRREGULAR')
  Diagnostico.create(tipo_diagnostico: 'Z6', despcripcion: 'NOTA: SE SUGIERE TRATAR ENDOMETRIO')
  Diagnostico.create(tipo_diagnostico: 'Z7', despcripcion: 'SE OBSERVAN NUCLEOS ENDOMETRIALES')
  Diagnostico.create(tipo_diagnostico: 'Z8', despcripcion: 'HIPERPLASIA DE CELULAS ENDOMETRIALES')
  Diagnostico.create(tipo_diagnostico: 'Z9', despcripcion: 'SE SUGIERE TINCION DE GRAMM')
end

#Area.create(nombre:'ALCATUYO  -  PUNA')
#Area.create(nombre:'CANTUMARCA')
#Area.create(nombre:'DELICIAS')
#Area.create(nombre:'PARI ORCKO')
#Area.create(nombre:'PLAN 40')
#Area.create(nombre:'PLAN 40  - PRO MUJER')
#Area.create(nombre:'SAN CRISTOBAL  -  PRO MUJER')
#Area.create(nombre:'SAN ROQUE   -  PRO MUJER')
#Area.create(nombre:'SAGRADA FAMILIA')
#Area.create(nombre:'SAN GERARDO')
#Area.create(nombre:'SAN CRISTOBAL')
#Area.create(nombre:'SAN ROQUE')
#Area.create(nombre:'VILLA VENEZUELA')
#Area.create(nombre:'VILLA COLÓN')
if Distrito.all.count == 0
  Distrito.create(nombre: 'URBANO')
  Distrito.create(nombre: 'RURAL')
  Distrito.create(nombre: 'BETANZOS')
  Distrito.create(nombre: 'COTAGAITA')
  Distrito.create(nombre: 'OCURI')
  Distrito.create(nombre: 'POTOSI   (URBANO)')
  Distrito.create(nombre: 'PUNA')
  Distrito.create(nombre: 'SACACA')
  Distrito.create(nombre: 'TUPIZA')
  Distrito.create(nombre: 'UNCIA')
  Distrito.create(nombre: 'UYUNI')
  Distrito.create(nombre: 'VILLAZON')
end
if Area.all.count == 0
  Area.create(nombre: 'ALCATUYO  -  PUNA')
  Area.create(nombre: 'CANTUMARCA')
  Area.create(nombre: 'DELICIAS')
  Area.create(nombre: 'PARI ORCKO')
  Area.create(nombre: 'PLAN 40')
  Area.create(nombre: 'PLAN 40  - PRO MUJER')
  Area.create(nombre: 'SAN CRISTOBAL  -  PRO MUJER')
  Area.create(nombre: 'SAN ROQUE   -  PRO MUJER')
  Area.create(nombre: 'SAGRADA FAMILIA')
  Area.create(nombre: 'SAN GERARDO')
  Area.create(nombre: 'SAN CRISTOBAL')
  Area.create(nombre: 'SAN ROQUE')
  Area.create(nombre: 'VILLA VENEZUELA')
  Area.create(nombre: 'VILLA COLÓN')
end
if Provincium.all.count == 0
  Provincium.create(nombre: 'ALONZO DE IBAÑEZ')
  Provincium.create(nombre: 'ANTONIO QUIJARRO')
  Provincium.create(nombre: 'BALDIVIESO')
  Provincium.create(nombre: 'BERNARDINO BILBAO')
  Provincium.create(nombre: 'CHARCAS')
  Provincium.create(nombre: 'CHAYANTA')
  Provincium.create(nombre: 'DANIEL CAMPOS')
  Provincium.create(nombre: 'JOSE MARIA LINARES')
  Provincium.create(nombre: 'MODESTO OMISTE')
  Provincium.create(nombre: 'NOR CHICHAS')
  Provincium.create(nombre: 'NOR LIPEZ')
  Provincium.create(nombre: 'RAFAEL BUSTILLO')
  Provincium.create(nombre: 'SAAVEDRA')
  Provincium.create(nombre: 'SUD CHICHAS')
  Provincium.create(nombre: 'SUD LIPEZ')
  Provincium.create(nombre: 'TOMAS FRIAS')
end
if Establecimiento.all.count == 0
  Establecimiento.create(nombre: 'NINGUNO')
  Establecimiento.create(nombre: 'ACACIO  -  C.S.  ACACIO')
  Establecimiento.create(nombre: 'ATOCHA  -  C.S.  ANIMAS')
  Establecimiento.create(nombre: 'ATOCHA  -  C.S.  ATOCHA')
  Establecimiento.create(nombre: 'ATOCHA  -  C.S.  TATASI')
  Establecimiento.create(nombre: 'ATOCHA  -  P.S.  TELAMAYU')
  Establecimiento.create(nombre: 'BELEN DE URMIRI  - C.S.  BELEN DE URMIRI')
  Establecimiento.create(nombre: 'BELEN DE URMIRI  -  P.S.  PUITUCO')
  Establecimiento.create(nombre: 'BELEN DE URMIRI  -  P.S.  VACUYO')
  Establecimiento.create(nombre: 'BETANZOS  -  HOSP. ROBERTO LOAYZA')
  Establecimiento.create(nombre: 'BETANZOS  -  C.S.  MAMAHOTA')
  Establecimiento.create(nombre: 'BETANZOS  -  C.S.  MILLARES')
  Establecimiento.create(nombre: 'BETANZOS  -  C.S.  POCO  POCO')
  Establecimiento.create(nombre: 'BETANZOS  -  P.S.  QUIVI QUIVI')
  Establecimiento.create(nombre: 'BETANZOS  -  C.S. TIRQUIBUCO')
  Establecimiento.create(nombre: 'BETANZOS   -  C.S.  VILLA  CARMEN')
  Establecimiento.create(nombre: 'BETANZOS  -  C.S.  CHAJPI GRANDE')
  Establecimiento.create(nombre: 'BETANZOS  -  P.S.  BUEY TAMBO')
  Establecimiento.create(nombre: 'BETANZOS  -  P.S.  MARIACA')
  Establecimiento.create(nombre: 'BETANZOS  -  P.S.  OTUYO')
  Establecimiento.create(nombre: 'BETANZOS  -  P.S.  QUIVINCHA')
  Establecimiento.create(nombre: 'BETANZOS  -  P.S.  SIPORO')
  Establecimiento.create(nombre: 'BETANZOS  -  P.S.  TIRISPAYA')
  Establecimiento.create(nombre: 'CAIZA  "D"  -  C.S.  CAIZA "D"')
  Establecimiento.create(nombre: 'CAIZA  "D"  -  C.S.  CUCHU INGENIO')
  Establecimiento.create(nombre: 'CAIZA  "D"  -  P.S.  ALCATUYO')
  Establecimiento.create(nombre: 'CAIZA  "D"  -  P.S.  CHILLMA')
  Establecimiento.create(nombre: 'CAIZA "D"  -  P.S.  FRAGUA')
  Establecimiento.create(nombre: 'CAIZA "D"  -  P.S.  HORNOS')
  Establecimiento.create(nombre: 'CAIZA  "D"  -  P.S.  HUICHACA')
  Establecimiento.create(nombre: 'CAIZA  "D"  - P.S.  LA LAVA')
  Establecimiento.create(nombre: 'CAIZA  "D"  -  C.S.  TRES CRUCES')
  Establecimiento.create(nombre: 'CARIPUYO  -  C.S.  CARIPUYO')
  Establecimiento.create(nombre: 'COLCHA  "K"  -  C.S. COLCHA "K"')
  Establecimiento.create(nombre: 'COLCHA  "K"  -  C.S.   SAN CRISTOBAL')
  Establecimiento.create(nombre: 'COLCHA  "K"  -  P.S.  CALCHA  "K"')
  Establecimiento.create(nombre: 'COLCHA  "K"  -  P.S.  POZO  CAVADO')
  Establecimiento.create(nombre: 'COLCHA  "K"  -  P.S.  RIO GRANDE')
  Establecimiento.create(nombre: 'COLQUECHACA  -  C.S.  COLQUECHACA')
  Establecimiento.create(nombre: 'COLQUECHACA  -  P.S.  CASTILLA HUMA')
  Establecimiento.create(nombre: 'COLQUECHACA  -  P.S.  SALINAS')
  Establecimiento.create(nombre: 'COLQUECHACA  -  P.S.  BOMBORI')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  CALVI')
  Establecimiento.create(nombre: 'COTAGAITA  -  C.S.  CKARA CARA')
  Establecimiento.create(nombre: 'COTAGAITA  -  C.S.  PALCA HIGUERAS')
  Establecimiento.create(nombre: 'COTAGAITA  -  C.S.  TOROPALCA')
  Establecimiento.create(nombre: 'COTAGAITA  -  C.S.  TUMUSLA')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  CALILA')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  CAZON')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  CHUI CHUI')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  COLLPA  UNO')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  ESCARA')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  JACOSCAPA')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  PAMPA GRANDE')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  TOCLA')
  Establecimiento.create(nombre: 'COTAGAITA  -  HOSP. SAN J DE DIOS')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  VICHACLA')
  Establecimiento.create(nombre: 'COTAGAITA  -  P.S.  VILLA CONCEPCIÓN')
  Establecimiento.create(nombre: 'CHAYANTA  -  C.S.  CHAYANTA')
  Establecimiento.create(nombre: 'CHAQUI  -  C.S.  CHAQUI')
  Establecimiento.create(nombre: 'CHAQUI  -  P.S.  CHICO CHICO')
  Establecimiento.create(nombre: 'CHAQUI  -  P.S.  DON DIEGO')
  Establecimiento.create(nombre: 'LLALLAGUA  -  HOSP.  MADRE OBRERA')
  Establecimiento.create(nombre: 'LLICA  -  C.S.  LLICA')
  Establecimiento.create(nombre: 'MOJINETE  -  P.S.  LA CIENEGA')
  Establecimiento.create(nombre: 'MOJINETE  -  C.S.  MOJITE')
  Establecimiento.create(nombre: 'OCURI  -  C.S.  CKARA CKARA')
  Establecimiento.create(nombre: 'OCURI  -  P.S.  MARAGUA')
  Establecimiento.create(nombre: 'POCOATA  -  C.S.  POCOATA')
  Establecimiento.create(nombre: 'POCOATA  -  PS.  SANTA BARBARA')
  Establecimiento.create(nombre: 'PORCO  -  C.S.  CORUMA')
  Establecimiento.create(nombre: 'PORCO  -  C.S.  CHAQUILLA')
  Establecimiento.create(nombre: 'PORCO  -  C.S.  AGUA DE CASTILLA')
  Establecimiento.create(nombre: 'PORCO  -  C.S.  PORCO')
  Establecimiento.create(nombre: 'PORCO  -  P.S.  CARMA')
  Establecimiento.create(nombre: 'POTOSI  -  C.S.  AZANGARO')
  Establecimiento.create(nombre: 'POTOSI  -  C.S.  HUARI  HUARI')
  Establecimiento.create(nombre: 'POTOSI  -  P.S.  CHAQUILLA')
  Establecimiento.create(nombre: 'POTOSI  - C.S.  TOMAVE')
  Establecimiento.create(nombre: 'PUNA  -  C.S.  CALAPAYA')
  Establecimiento.create(nombre: 'PUNA  -  C.S.  CHECCHI')
  Establecimiento.create(nombre: 'PUNA  -  C.S.  CHINOLI')
  Establecimiento.create(nombre: 'PUNA  -  C.S.  CKOCHAS')
  Establecimiento.create(nombre: 'PUNA  -  C.S. KELUYO')
  Establecimiento.create(nombre: 'PUNA  -  C.S.  KEPALLO')
  Establecimiento.create(nombre: 'PUNA  -  C.S.  PACASI')
  Establecimiento.create(nombre: 'PUNA  -  C.S.  PUNA')
  Establecimiento.create(nombre: 'PUNA  -  C.S.  TURUCHIPA')
  Establecimiento.create(nombre: 'PUNA  -  P.S.  ESMERALDA ALTA')
  Establecimiento.create(nombre: 'PUNA  -  P.S.  SAN P. ESQUIRI')
  Establecimiento.create(nombre: 'PUNA  -  P.S.  SUQUICHA')
  Establecimiento.create(nombre: 'PUNA  -  P.S.  SUQUICHA')
  Establecimiento.create(nombre: 'PUNA  -  P.S.  YASCAPI')
  Establecimiento.create(nombre: 'PUNA  -  P.S.  ÑUQUI')
  Establecimiento.create(nombre: 'RAVELO  -  C.S.  RAVELO')
  Establecimiento.create(nombre: 'RAVELO  -  P.S.  YACURI')
  Establecimiento.create(nombre: 'SACACA  -  C.S.  SACACA')
  Establecimiento.create(nombre: 'SAN AGUSTIN  -  C.S.  SAN AGUSTIN')
  Establecimiento.create(nombre: 'SAN A. DE ESMORUCO  - P.S. RIO MOJON')
  Establecimiento.create(nombre: 'SAN A. DE ESMORUCO - C.S.S.A. DE ESMORUCO')
  Establecimiento.create(nombre: 'SAN P. DE LIPEZ  -  P.S. QUETENA CHICO')
  Establecimiento.create(nombre: 'SAN P. DE LIPEZ  -  C.S.  VILUYO')
  Establecimiento.create(nombre: 'TACOBAMBA  -  P.S.  KILPANI')
  Establecimiento.create(nombre: 'TACOBAMBA  -  P.S.  TACORA')
  Establecimiento.create(nombre: 'TACOBAMBA  -  C.S.  TACOBAMBA')
  Establecimiento.create(nombre: 'TACOBAMBA  -  P.S.  MIGMA')
  Establecimiento.create(nombre: 'TAHUA  -  C.S.  TAHUA')
  Establecimiento.create(nombre: 'TAHUA  - P.S.  CAQUENA')
  Establecimiento.create(nombre: 'TAHUA  -  P.S.  YONZA')
  Establecimiento.create(nombre: 'TINGUIPAYA  -  C.S.  TINGUIPAYA')
  Establecimiento.create(nombre: 'TOMAVE  -  C.S.  P.S.  YURA')
  Establecimiento.create(nombre: 'TOMAVE  -  P.S.  TOMAVE')
  Establecimiento.create(nombre: 'TUPIZA  -  C.S.  RIO BLANCO')
  Establecimiento.create(nombre: 'TUPIZA  -  C.S.  CHUQUIAGO')
  Establecimiento.create(nombre: 'TUPIZA  -  C.S.  ESMORACA')
  Establecimiento.create(nombre: 'TUPIZA  -  C.S.  ESTARCA')
  Establecimiento.create(nombre: 'TUPIZA  -  C.S.   OPLOCA')
  Establecimiento.create(nombre: 'TUPIZA  -  C.S.  SAN ANTONIO')
  Establecimiento.create(nombre: 'TUPIZA  -  C.S.  SAN GERARDO')
  Establecimiento.create(nombre: 'TUPIZA  -  C.S.  SUD')
  Establecimiento.create(nombre: 'TUPIZA  -  C.S.  TALINA')
  Establecimiento.create(nombre: 'TUPIZA  -  C.S.  TUPIZA')
  Establecimiento.create(nombre: 'TUPIZA   -  C.S. VILLA FATIMA')
  Establecimiento.create(nombre: 'TUPIZA  -  HOSP. EDUARDO EGUIA')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  ALTO MAMAHOTA')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  CHACOPAMPA')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  HUMACHA')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  NAZARENO')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  ORO INGENIO')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  PEÑA AMARILLA')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  PIEDRAS BLANCAS')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  QUIRIZA')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  REYNECILLAS')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  SALO')
  Establecimiento.create(nombre: 'TUPIZA  .  P.S. S.J.PAMPA GRANDE')
  Establecimiento.create(nombre: 'TUPIZA - P.S.  SAN MIGUEL')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  SUPIRA')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  TAPAXA')
  Establecimiento.create(nombre: 'TUPIZA  -  P.S.  TOCLOCA')
  Establecimiento.create(nombre: 'TUPIZA  -  HOSP. CIVIL TUPÌZA')
  Establecimiento.create(nombre: 'TUPIZA  -  HOSP. CORNACA')
  Establecimiento.create(nombre: 'UNCIA  -  C.S.  CHUQUIUTA')
  Establecimiento.create(nombre: 'UNCIA  -  C.S.  UNCIA')
  Establecimiento.create(nombre: 'UNCIA  -  HOSP. BUEN SAMARITANO')
  Establecimiento.create(nombre: 'UYUNI  -  C.S.  RIO MULATO')
  Establecimiento.create(nombre: 'UYUNI  -  C.S.  UYUNI')
  Establecimiento.create(nombre: 'UYUNI  -   HOSP. JOSE E. PEREZ')
  Establecimiento.create(nombre: 'VILLAZON  -  HOSP.  ELIODORO VILLAZON')
  Establecimiento.create(nombre: 'VILLAZON  -  C.S.  SAN JUAN DE DIOS')
  Establecimiento.create(nombre: 'VILLAZON  -  C.S.  SAN JUDAS TADEO')
  Establecimiento.create(nombre: 'VILLAZON  -  C.S.  SAN MARTIN')
  Establecimiento.create(nombre: 'VILLAZON  -  HOSP.  SAN ROQUE')
  Establecimiento.create(nombre: 'VILLAZON  -  P.S.  BERQUE')
  Establecimiento.create(nombre: 'VILLAZON  -  P.S.  CASIRA')
  Establecimiento.create(nombre: 'VILLAZON  -  P.S.  MORAYA')
  Establecimiento.create(nombre: 'VILLAZON  -  P.S.  MOJO')
  Establecimiento.create(nombre: 'VILLAZON  -  P.S.  VILLA CARMEN')
  Establecimiento.create(nombre: 'VITICHI  -  HOSP. BUEN SAMARITANO')
  Establecimiento.create(nombre: 'VITICHI  -  C.S.  CALCHA')
  Establecimiento.create(nombre: 'VITICHI  -  C.S.  YAWISLA')
  Establecimiento.create(nombre: 'VITICHI  -  C.S.  VITICHI')
  Establecimiento.create(nombre: 'VITICHI  -  P.S.  ARIPALCA')
  Establecimiento.create(nombre: 'VITICHI  -  P.S.  PECKA')
  Establecimiento.create(nombre: 'VITICHI  -  P.S.  PEKAJSI')
  Establecimiento.create(nombre: 'VITICHI  -  P.S.  SAN ANTONIO')
  Establecimiento.create(nombre: 'VITICHI  -  P.S.  TUSQUIÑA')
  Establecimiento.create(nombre: 'VITICHI  -  P.S.  YULO')
  Establecimiento.create(nombre: 'VITICHI  -  HOSP. S. VICENTE POOL')
  Establecimiento.create(nombre: 'YOCALLA  -  C.S.  YOCALLA')
  Establecimiento.create(nombre: 'YOCALLA  -  P.S.  CAYARA')
  Establecimiento.create(nombre: 'YOCALLA  -  P.S.  CHIRACORO')
  Establecimiento.create(nombre: 'YOCALLA  -  P.S.  TOTORA D')
end